In [1]:
import pandas as pd
import sqlite3

In [8]:
df_cleaned = pd.read_excel("Cleaned_Dataset_Project1_Final.xlsx")

In [9]:
conn = sqlite3.connect(':memory:')

In [10]:
df_cleaned.to_sql('ecommerce_sales', conn, index=False, if_exists='replace')

1200

In [11]:
# Testing Aggregation Queries
# Function to cleanly format and print SQL query data tables
def run_query(query):
    return pd.read_sql_query(query, conn)

In [15]:
# Test query for product portfolio summaries
product_query = """
SELECT 
    Product,
    COUNT(OrderID) AS Total_Orders,
    ROUND(AVG(TotalPrice), 2) AS Avg_Order_Value,
    ROUND(SUM(TotalPrice), 2) AS Total_Revenue
FROM ecommerce_sales 
GROUP BY Product
ORDER BY Total_Revenue DESC;
"""

In [16]:
run_query(product_query)

   Product  Total_Orders  Avg_Order_Value  Total_Revenue
0    Chair           178          1098.99      195620.11
1  Printer           181          1080.73      195612.61
2   Laptop           173          1110.56      192126.56
3   Tablet           179          1042.28      186568.95
4  Monitor           163          1077.62      175651.41
5     Desk           170           985.06      167459.93
6    Phone           156           972.58      151722.39

In [19]:
#Uncovering Top Customer Referral Sources
referral_query = """
SELECT 
    ReferralSource,
    COUNT(OrderID) AS Direct_Acquisitions,
    ROUND(SUM(TotalPrice), 2) AS Channels_Attributed_Revenue
FROM ecommerce_sales
GROUP BY ReferralSource
ORDER BY Channels_Attributed_Revenue DESC;
"""

In [20]:
run_query(referral_query)

  ReferralSource  Direct_Acquisitions  Channels_Attributed_Revenue
0      Instagram                  259                    275285.45
1          Email                  250                    261808.55
2         Google                  241                    250441.48
3       Facebook                  228                    250410.90
4       Referral                  222                    226815.58